apiVersion: apps.3scale.net/v1alpha1
kind: APIManager
metadata:
  namespace: amp
  name: my-apimanager
spec:
  imageStreamTagImportInsecure: true
  system:
    image: >-
      [oracle-system-image-url]
  highAvailability:
    enabled: true
  wildcardDomain: [openshift-cluster-wildcard]