---
apiVersion: v1
kind: Secret
metadata:
  name: backend-redis
stringData:
  REDIS_STORAGE_URL: "redis://[redis-sentinel-group-name]:6379"
  REDIS_STORAGE_SENTINEL_HOSTS: "redis://[redis-sentinel-host-1]:26379,redis://[redis-sentinel-host-2]:26379,redis://[redis-sentinel-host-3]:26379"
  REDIS_STORAGE_SENTINEL_ROLE: "master"
  REDIS_QUEUES_URL: "redis://[redis-sentinel-group-name]:6379"
  REDIS_QUEUES_SENTINEL_HOSTS: "redis://[redis-sentinel-host-1]:26379,redis://[redis-sentinel-host-2]:26379,redis://[redis-sentinel-host-3]:26379"
  REDIS_QUEUES_SENTINEL_ROLE: "master"
