---
apiVersion: v1
kind: Secret
metadata:
  name: system-database
stringData:
  URL: "oracle-enhanced://<user>:<password>@<oracle-host>:1521/<sid>"
  ORACLE_SYSTEM_PASSWORD: "<system-password>"
type: Opaque
