---
apiVersion: v1
kind: Secret
metadata:
  name: system-redis
stringData:
  URL: "redis://redis-master:6379"
  SENTINEL_HOSTS: "redis://3.91.197.24:26379,redis://54.227.39.199:26379,redis://52.207.137.253:26379"
  SENTINEL_ROLE: "master"
  NAMESPACE: ""
  MESSAGE_BUS_URL: "redis://redis-master:6379"
  MESSAGE_BUS_SENTINEL_HOSTS: "redis://3.91.197.24:26379,redis://54.227.39.199:26379,redis://52.207.137.253:26379"
  MESSAGE_BUS_SENTINEL_ROLE: "master"
  MESSAGE_BUS_NAMESPACE: ""
type: Opaque
