---
apiVersion: v1
kind: Secret
metadata:
  name: system-redis
stringData:
  URL: "redis://[redis-sentinel-group-name]:6379"
  SENTINEL_HOSTS: "redis://[redis-sentinel-host-1]:26379,redis://[redis-sentinel-host-2]:26379,redis://[redis-sentinel-host-3]:26379"
  SENTINEL_ROLE: "master"
  NAMESPACE: ""
  MESSAGE_BUS_URL: "redis://[redis-sentinel-group-name]:6379"
  MESSAGE_BUS_SENTINEL_HOSTS: "redis://[redis-sentinel-host-1]:26379,redis://[redis-sentinel-host-2]:26379,redis://[redis-sentinel-host-3]:26379"
  MESSAGE_BUS_SENTINEL_ROLE: "master"
  MESSAGE_BUS_NAMESPACE: ""
type: Opaque
