---
apiVersion: v1
kind: Secret
metadata:
  name: system-database
stringData:
  URL: "oracle-enhanced://[oracle-user]:[oracle-password]@[oracle-host]:1521/[oracle-sid]"
  ORACLE_SYSTEM_PASSWORD: "[oracle-system-password]"
type: Opaque
